title: Varberg Popcorn
description: >
  Tester för en mer värdefull framtid
author: Anders Dalén
email: anders.dalen@ri.se

baseurl: /popcorn
collections:
  needs:
    output: true
  solutions:
    output: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
